/**
 * AUTO-GENERATED by scripts/generate-pi-grid.ts — do not edit manually.
 * Generated at: 2026-07-12T14:41:14.767Z
 *
 * CPU / Powergrid figures for Planetary Industry, sourced from live ESI dogma
 * (attributes 11/48 output, 15/49 load, 1690/1691 extractor head). Every number
 * here is a real ESI value — the CC budget per upgrade level (0..5) is read from
 * the legacy named Command Center types and asserted consistent across planets.
 */
export interface PiGridCost {
  /** Powergrid in MW. */
  power: number
  /** CPU in tf. */
  cpu: number
}

/** Per-structure grid LOAD (consumption) by pin type_id, from ESI powerLoad/cpuLoad. */
export const PI_PIN_GRID: Record<number, PiGridCost> = {
  "2256": {
    "power": 700,
    "cpu": 3600
  },
  "2257": {
    "power": 700,
    "cpu": 500
  },
  "2469": {
    "power": 800,
    "cpu": 200
  },
  "2470": {
    "power": 700,
    "cpu": 500
  },
  "2471": {
    "power": 800,
    "cpu": 200
  },
  "2472": {
    "power": 700,
    "cpu": 500
  },
  "2473": {
    "power": 800,
    "cpu": 200
  },
  "2474": {
    "power": 700,
    "cpu": 500
  },
  "2475": {
    "power": 400,
    "cpu": 1100
  },
  "2480": {
    "power": 700,
    "cpu": 500
  },
  "2481": {
    "power": 800,
    "cpu": 200
  },
  "2482": {
    "power": 400,
    "cpu": 1100
  },
  "2483": {
    "power": 800,
    "cpu": 200
  },
  "2484": {
    "power": 700,
    "cpu": 500
  },
  "2485": {
    "power": 700,
    "cpu": 500
  },
  "2490": {
    "power": 800,
    "cpu": 200
  },
  "2491": {
    "power": 700,
    "cpu": 500
  },
  "2492": {
    "power": 800,
    "cpu": 200
  },
  "2493": {
    "power": 800,
    "cpu": 200
  },
  "2494": {
    "power": 700,
    "cpu": 500
  },
  "2535": {
    "power": 700,
    "cpu": 500
  },
  "2536": {
    "power": 700,
    "cpu": 500
  },
  "2541": {
    "power": 700,
    "cpu": 500
  },
  "2542": {
    "power": 700,
    "cpu": 3600
  },
  "2543": {
    "power": 700,
    "cpu": 3600
  },
  "2544": {
    "power": 700,
    "cpu": 3600
  },
  "2552": {
    "power": 700,
    "cpu": 3600
  },
  "2555": {
    "power": 700,
    "cpu": 3600
  },
  "2556": {
    "power": 700,
    "cpu": 3600
  },
  "2557": {
    "power": 700,
    "cpu": 3600
  },
  "2558": {
    "power": 700,
    "cpu": 500
  },
  "2560": {
    "power": 700,
    "cpu": 500
  },
  "2561": {
    "power": 700,
    "cpu": 500
  },
  "2562": {
    "power": 700,
    "cpu": 500
  },
  "2848": {
    "power": 2600,
    "cpu": 400
  },
  "3060": {
    "power": 2600,
    "cpu": 400
  },
  "3061": {
    "power": 2600,
    "cpu": 400
  },
  "3062": {
    "power": 2600,
    "cpu": 400
  },
  "3063": {
    "power": 2600,
    "cpu": 400
  },
  "3064": {
    "power": 2600,
    "cpu": 400
  },
  "3067": {
    "power": 2600,
    "cpu": 400
  },
  "3068": {
    "power": 2600,
    "cpu": 400
  }
}

/** Additional grid load per installed extractor head, by ECU type_id (ESI 1690/1691). */
export const PI_EXTRACTOR_HEAD_COST: Record<number, PiGridCost> = {
  "2848": {
    "power": 550,
    "cpu": 110
  },
  "3060": {
    "power": 550,
    "cpu": 110
  },
  "3061": {
    "power": 550,
    "cpu": 110
  },
  "3062": {
    "power": 550,
    "cpu": 110
  },
  "3063": {
    "power": 550,
    "cpu": 110
  },
  "3064": {
    "power": 550,
    "cpu": 110
  },
  "3067": {
    "power": 550,
    "cpu": 110
  },
  "3068": {
    "power": 550,
    "cpu": 110
  }
}

/** Command Center grid budget by upgrade level (0..5). Level 0 from ESI dogma. */
export const CC_GRID_BY_LEVEL: Record<number, PiGridCost> = {
  "0": {
    "power": 6000,
    "cpu": 1675
  },
  "1": {
    "power": 9000,
    "cpu": 7057
  },
  "2": {
    "power": 12000,
    "cpu": 12136
  },
  "3": {
    "power": 15000,
    "cpu": 17215
  },
  "4": {
    "power": 17000,
    "cpu": 21315
  },
  "5": {
    "power": 19000,
    "cpu": 25415
  }
}

/** Level-0 CC base budget (uniform across planet types on ESI). */
export const CC_GRID_BASE: PiGridCost = {
  "power": 6000,
  "cpu": 1675
}

export function ccGridBudget(upgradeLevel: number): PiGridCost {
  return CC_GRID_BY_LEVEL[upgradeLevel] ?? CC_GRID_BY_LEVEL[0]!
}

export function pinGridLoad(typeId: number): PiGridCost {
  return PI_PIN_GRID[typeId] ?? { power: 0, cpu: 0 }
}

export function extractorHeadCost(typeId: number): PiGridCost {
  return PI_EXTRACTOR_HEAD_COST[typeId] ?? { power: 0, cpu: 0 }
}
