/**
 * AUTO-GENERATED by scripts/generate-pi-data.ts — do not edit manually.
 * Generated at: 2026-06-16T18:52:15.876Z
 */
export type PiCommodityTier = 0 | 1 | 2 | 3 | 4

export type PiPinRole =
  | 'command_center'
  | 'extractor'
  | 'basic_processor'
  | 'advanced_processor'
  | 'high_tech_processor'
  | 'storage'
  | 'launchpad'
  | 'link'
  | 'unknown'

export interface PiSchematic {
  id: number
  name: string
  cycleTimeSec: number
  output: { typeId: number; qty: number }
  inputs: Array<{ typeId: number; qty: number }>
  pinTypeIds: number[]
}

export const PI_SCHEMATICS: Record<number, PiSchematic> = {
  "65": {
    "id": 65,
    "name": "Superconductors",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9838,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2389,
        "qty": 40
      },
      {
        "typeId": 3645,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "66": {
    "id": 66,
    "name": "Coolant",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9832,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2390,
        "qty": 40
      },
      {
        "typeId": 3645,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "67": {
    "id": 67,
    "name": "Rocket Fuel",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9830,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2389,
        "qty": 40
      },
      {
        "typeId": 2390,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "68": {
    "id": 68,
    "name": "Synthetic Oil",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3691,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2390,
        "qty": 40
      },
      {
        "typeId": 3683,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "69": {
    "id": 69,
    "name": "Oxides",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2317,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2392,
        "qty": 40
      },
      {
        "typeId": 3683,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "70": {
    "id": 70,
    "name": "Silicate Glass",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3697,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2392,
        "qty": 40
      },
      {
        "typeId": 9828,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "71": {
    "id": 71,
    "name": "Transmitter",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9840,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2389,
        "qty": 40
      },
      {
        "typeId": 2401,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "72": {
    "id": 72,
    "name": "Water-Cooled CPU",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2328,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2398,
        "qty": 40
      },
      {
        "typeId": 3645,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "73": {
    "id": 73,
    "name": "Mechanical Parts",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3689,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2398,
        "qty": 40
      },
      {
        "typeId": 2399,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "74": {
    "id": 74,
    "name": "Construction Blocks",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3828,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2398,
        "qty": 40
      },
      {
        "typeId": 2400,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "75": {
    "id": 75,
    "name": "Enriched Uranium",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 44,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2399,
        "qty": 40
      },
      {
        "typeId": 2400,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "76": {
    "id": 76,
    "name": "Consumer Electronics",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9836,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2400,
        "qty": 40
      },
      {
        "typeId": 2401,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "77": {
    "id": 77,
    "name": "Miniature Electronics",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9842,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2401,
        "qty": 40
      },
      {
        "typeId": 9828,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "78": {
    "id": 78,
    "name": "Nanites",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2463,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2393,
        "qty": 40
      },
      {
        "typeId": 2398,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "79": {
    "id": 79,
    "name": "Biocells",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2329,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2396,
        "qty": 40
      },
      {
        "typeId": 2399,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "80": {
    "id": 80,
    "name": "Microfiber Shielding",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2327,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2397,
        "qty": 40
      },
      {
        "typeId": 9828,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "81": {
    "id": 81,
    "name": "Viral Agent",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3775,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2393,
        "qty": 40
      },
      {
        "typeId": 3779,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "82": {
    "id": 82,
    "name": "Fertilizer",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3693,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2393,
        "qty": 40
      },
      {
        "typeId": 2395,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "83": {
    "id": 83,
    "name": "Genetically Enhanced Livestock",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 15317,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2395,
        "qty": 40
      },
      {
        "typeId": 3779,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "84": {
    "id": 84,
    "name": "Livestock",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3725,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2395,
        "qty": 40
      },
      {
        "typeId": 2396,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "85": {
    "id": 85,
    "name": "Polytextiles",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 3695,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2396,
        "qty": 40
      },
      {
        "typeId": 2397,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "86": {
    "id": 86,
    "name": "Test Cultures",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2319,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2393,
        "qty": 40
      },
      {
        "typeId": 3645,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "87": {
    "id": 87,
    "name": "Supertensile Plastics",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2312,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 3683,
        "qty": 40
      },
      {
        "typeId": 3779,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "88": {
    "id": 88,
    "name": "Polyaramids",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2321,
      "qty": 5
    },
    "inputs": [
      {
        "typeId": 2392,
        "qty": 40
      },
      {
        "typeId": 2397,
        "qty": 40
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "89": {
    "id": 89,
    "name": "Ukomi Superconductor",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 17136,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 3691,
        "qty": 10
      },
      {
        "typeId": 9838,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "90": {
    "id": 90,
    "name": "Condensates",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2344,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2317,
        "qty": 10
      },
      {
        "typeId": 9832,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "91": {
    "id": 91,
    "name": "Camera Drones",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2345,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 3697,
        "qty": 10
      },
      {
        "typeId": 9830,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "92": {
    "id": 92,
    "name": "Synthetic Synapses",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2346,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2312,
        "qty": 10
      },
      {
        "typeId": 2319,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "94": {
    "id": 94,
    "name": "High-Tech Transmitter",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 17898,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2321,
        "qty": 10
      },
      {
        "typeId": 9840,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "95": {
    "id": 95,
    "name": "Gel-Matrix Biopaste",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2348,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2317,
        "qty": 10
      },
      {
        "typeId": 2329,
        "qty": 10
      },
      {
        "typeId": 9838,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "96": {
    "id": 96,
    "name": "Supercomputers",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2349,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2328,
        "qty": 10
      },
      {
        "typeId": 9832,
        "qty": 10
      },
      {
        "typeId": 9836,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "97": {
    "id": 97,
    "name": "Robotics",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9848,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 3689,
        "qty": 10
      },
      {
        "typeId": 9836,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "98": {
    "id": 98,
    "name": "Smartfab Units",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2351,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 3828,
        "qty": 10
      },
      {
        "typeId": 9842,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "99": {
    "id": 99,
    "name": "Nuclear Reactors",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2352,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 44,
        "qty": 10
      },
      {
        "typeId": 2327,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "100": {
    "id": 100,
    "name": "Guidance Systems",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9834,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2328,
        "qty": 10
      },
      {
        "typeId": 9840,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "102": {
    "id": 102,
    "name": "Neocoms",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2354,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2329,
        "qty": 10
      },
      {
        "typeId": 3697,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "103": {
    "id": 103,
    "name": "Planetary Vehicles",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 9846,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2312,
        "qty": 10
      },
      {
        "typeId": 3689,
        "qty": 10
      },
      {
        "typeId": 9842,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "104": {
    "id": 104,
    "name": "Biotech Research Reports",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2358,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2463,
        "qty": 10
      },
      {
        "typeId": 3725,
        "qty": 10
      },
      {
        "typeId": 3828,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "105": {
    "id": 105,
    "name": "Vaccines",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 28974,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 3725,
        "qty": 10
      },
      {
        "typeId": 3775,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "106": {
    "id": 106,
    "name": "Industrial Explosives",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2360,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 3693,
        "qty": 10
      },
      {
        "typeId": 3695,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "107": {
    "id": 107,
    "name": "Hermetic Membranes",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2361,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2321,
        "qty": 10
      },
      {
        "typeId": 15317,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "108": {
    "id": 108,
    "name": "Transcranial Microcontroller",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 12836,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2329,
        "qty": 10
      },
      {
        "typeId": 2463,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "109": {
    "id": 109,
    "name": "Data Chips",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 17392,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2312,
        "qty": 10
      },
      {
        "typeId": 2327,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "110": {
    "id": 110,
    "name": "Hazmat Detection Systems",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2366,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 3695,
        "qty": 10
      },
      {
        "typeId": 3775,
        "qty": 10
      },
      {
        "typeId": 9840,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "111": {
    "id": 111,
    "name": "Cryoprotectant Solution",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2367,
      "qty": 3
    },
    "inputs": [
      {
        "typeId": 2319,
        "qty": 10
      },
      {
        "typeId": 3691,
        "qty": 10
      },
      {
        "typeId": 3693,
        "qty": 10
      }
    ],
    "pinTypeIds": [
      2470,
      2472,
      2474,
      2480,
      2484,
      2485,
      2491,
      2494
    ]
  },
  "112": {
    "id": 112,
    "name": "Organic Mortar Applicators",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2870,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2344,
        "qty": 6
      },
      {
        "typeId": 2393,
        "qty": 40
      },
      {
        "typeId": 9848,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "113": {
    "id": 113,
    "name": "Sterile Conduits",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2875,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2351,
        "qty": 6
      },
      {
        "typeId": 3645,
        "qty": 40
      },
      {
        "typeId": 28974,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "114": {
    "id": 114,
    "name": "Nano-Factory",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2869,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2360,
        "qty": 6
      },
      {
        "typeId": 2398,
        "qty": 40
      },
      {
        "typeId": 17136,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "115": {
    "id": 115,
    "name": "Self-Harmonizing Power Core",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2872,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2345,
        "qty": 6
      },
      {
        "typeId": 2352,
        "qty": 6
      },
      {
        "typeId": 2361,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "116": {
    "id": 116,
    "name": "Recursive Computing Module",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2871,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2346,
        "qty": 6
      },
      {
        "typeId": 9834,
        "qty": 6
      },
      {
        "typeId": 12836,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "117": {
    "id": 117,
    "name": "Broadcast Node",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2867,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2354,
        "qty": 6
      },
      {
        "typeId": 17392,
        "qty": 6
      },
      {
        "typeId": 17898,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "118": {
    "id": 118,
    "name": "Integrity Response Drones",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2868,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2348,
        "qty": 6
      },
      {
        "typeId": 2366,
        "qty": 6
      },
      {
        "typeId": 9846,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "119": {
    "id": 119,
    "name": "Wetware Mainframe",
    "cycleTimeSec": 3600,
    "output": {
      "typeId": 2876,
      "qty": 1
    },
    "inputs": [
      {
        "typeId": 2349,
        "qty": 6
      },
      {
        "typeId": 2358,
        "qty": 6
      },
      {
        "typeId": 2367,
        "qty": 6
      }
    ],
    "pinTypeIds": [
      2475,
      2482
    ]
  },
  "121": {
    "id": 121,
    "name": "Water",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 3645,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2268,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "122": {
    "id": 122,
    "name": "Plasmoids",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2389,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2308,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "123": {
    "id": 123,
    "name": "Electrolytes",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2390,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2309,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "124": {
    "id": 124,
    "name": "Oxygen",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 3683,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2310,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "125": {
    "id": 125,
    "name": "Oxidizing Compound",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2392,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2311,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "126": {
    "id": 126,
    "name": "Reactive Metals",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2398,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2267,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "127": {
    "id": 127,
    "name": "Precious Metals",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2399,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2270,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "128": {
    "id": 128,
    "name": "Toxic Metals",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2400,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2272,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "129": {
    "id": 129,
    "name": "Chiral Structures",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2401,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2306,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "130": {
    "id": 130,
    "name": "Silicon",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 9828,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2307,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "131": {
    "id": 131,
    "name": "Bacteria",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2393,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2073,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "132": {
    "id": 132,
    "name": "Biomass",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 3779,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2286,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "133": {
    "id": 133,
    "name": "Proteins",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2395,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2287,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "134": {
    "id": 134,
    "name": "Biofuels",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2396,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2288,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  },
  "135": {
    "id": 135,
    "name": "Industrial Fibers",
    "cycleTimeSec": 1800,
    "output": {
      "typeId": 2397,
      "qty": 20
    },
    "inputs": [
      {
        "typeId": 2305,
        "qty": 3000
      }
    ],
    "pinTypeIds": [
      2469,
      2471,
      2473,
      2481,
      2483,
      2490,
      2492,
      2493
    ]
  }
}

export const PI_COMMODITY_TIER: Record<number, PiCommodityTier> = {
  "44": 2,
  "2073": 0,
  "2267": 0,
  "2268": 0,
  "2270": 0,
  "2272": 0,
  "2286": 0,
  "2287": 0,
  "2288": 0,
  "2305": 0,
  "2306": 0,
  "2307": 0,
  "2308": 0,
  "2309": 0,
  "2310": 0,
  "2311": 0,
  "2312": 2,
  "2317": 1,
  "2319": 2,
  "2321": 1,
  "2327": 1,
  "2328": 2,
  "2329": 2,
  "2344": 3,
  "2345": 2,
  "2346": 3,
  "2348": 3,
  "2349": 3,
  "2351": 3,
  "2352": 3,
  "2354": 3,
  "2358": 3,
  "2360": 3,
  "2361": 3,
  "2366": 3,
  "2367": 3,
  "2389": 0,
  "2390": 0,
  "2392": 0,
  "2393": 1,
  "2395": 1,
  "2396": 1,
  "2397": 0,
  "2398": 1,
  "2399": 1,
  "2400": 1,
  "2401": 0,
  "2463": 2,
  "2867": 4,
  "2868": 4,
  "2869": 4,
  "2870": 4,
  "2871": 4,
  "2872": 4,
  "2875": 4,
  "2876": 4,
  "3645": 1,
  "3683": 0,
  "3689": 2,
  "3691": 1,
  "3693": 2,
  "3695": 2,
  "3697": 1,
  "3725": 2,
  "3775": 2,
  "3779": 1,
  "3828": 2,
  "9828": 0,
  "9830": 1,
  "9832": 2,
  "9834": 3,
  "9836": 2,
  "9838": 2,
  "9840": 2,
  "9842": 2,
  "9846": 3,
  "9848": 3,
  "12836": 3,
  "15317": 2,
  "17136": 3,
  "17392": 3,
  "17898": 3,
  "28974": 3
}

export const PI_COMMODITY_NAMES: Record<number, string> = {
  "44": "Enriched Uranium",
  "2073": "Microorganisms",
  "2267": "Base Metals",
  "2268": "Aqueous Liquids",
  "2270": "Noble Metals",
  "2272": "Heavy Metals",
  "2286": "Planktic Colonies",
  "2287": "Complex Organisms",
  "2288": "Carbon Compounds",
  "2305": "Autotrophs",
  "2306": "Non-CS Crystals",
  "2307": "Felsic Magma",
  "2308": "Suspended Plasma",
  "2309": "Ionic Solutions",
  "2310": "Noble Gas",
  "2311": "Reactive Gas",
  "2312": "Supertensile Plastics",
  "2317": "Oxides",
  "2319": "Test Cultures",
  "2321": "Polyaramids",
  "2327": "Microfiber Shielding",
  "2328": "Water-Cooled CPU",
  "2329": "Biocells",
  "2344": "Condensates",
  "2345": "Camera Drones",
  "2346": "Synthetic Synapses",
  "2348": "Gel-Matrix Biopaste",
  "2349": "Supercomputers",
  "2351": "Smartfab Units",
  "2352": "Nuclear Reactors",
  "2354": "Neocoms",
  "2358": "Biotech Research Reports",
  "2360": "Industrial Explosives",
  "2361": "Hermetic Membranes",
  "2366": "Hazmat Detection Systems",
  "2367": "Cryoprotectant Solution",
  "2389": "Plasmoids",
  "2390": "Electrolytes",
  "2392": "Oxidizing Compound",
  "2393": "Bacteria",
  "2395": "Proteins",
  "2396": "Biofuels",
  "2397": "Industrial Fibers",
  "2398": "Reactive Metals",
  "2399": "Precious Metals",
  "2400": "Toxic Metals",
  "2401": "Chiral Structures",
  "2463": "Nanites",
  "2867": "Broadcast Node",
  "2868": "Integrity Response Drones",
  "2869": "Nano-Factory",
  "2870": "Organic Mortar Applicators",
  "2871": "Recursive Computing Module",
  "2872": "Self-Harmonizing Power Core",
  "2875": "Sterile Conduits",
  "2876": "Wetware Mainframe",
  "3645": "Water",
  "3683": "Oxygen",
  "3689": "Mechanical Parts",
  "3691": "Synthetic Oil",
  "3693": "Fertilizer",
  "3695": "Polytextiles",
  "3697": "Silicate Glass",
  "3725": "Livestock",
  "3775": "Viral Agent",
  "3779": "Biomass",
  "3828": "Construction Blocks",
  "9828": "Silicon",
  "9830": "Rocket Fuel",
  "9832": "Coolant",
  "9834": "Guidance Systems",
  "9836": "Consumer Electronics",
  "9838": "Superconductors",
  "9840": "Transmitter",
  "9842": "Miniature Electronics",
  "9846": "Planetary Vehicles",
  "9848": "Robotics",
  "12836": "Transcranial Microcontrollers",
  "15317": "Genetically Enhanced Livestock",
  "17136": "Ukomi Superconductors",
  "17392": "Data Chips",
  "17898": "High-Tech Transmitters",
  "28974": "Vaccines"
}

export const PIN_ROLES: Record<number, PiPinRole> = {
  "2129": "command_center",
  "2130": "command_center",
  "2131": "command_center",
  "2132": "command_center",
  "2133": "command_center",
  "2134": "command_center",
  "2135": "command_center",
  "2136": "command_center",
  "2137": "command_center",
  "2138": "command_center",
  "2139": "command_center",
  "2140": "command_center",
  "2141": "command_center",
  "2142": "command_center",
  "2143": "command_center",
  "2144": "command_center",
  "2145": "command_center",
  "2146": "command_center",
  "2147": "command_center",
  "2148": "command_center",
  "2149": "command_center",
  "2150": "command_center",
  "2151": "command_center",
  "2152": "command_center",
  "2153": "command_center",
  "2154": "command_center",
  "2155": "command_center",
  "2156": "command_center",
  "2157": "command_center",
  "2158": "command_center",
  "2159": "command_center",
  "2160": "command_center",
  "2254": "command_center",
  "2256": "launchpad",
  "2257": "storage",
  "2469": "basic_processor",
  "2470": "advanced_processor",
  "2471": "basic_processor",
  "2472": "advanced_processor",
  "2473": "basic_processor",
  "2474": "advanced_processor",
  "2475": "high_tech_processor",
  "2480": "advanced_processor",
  "2481": "basic_processor",
  "2482": "high_tech_processor",
  "2483": "basic_processor",
  "2484": "advanced_processor",
  "2485": "advanced_processor",
  "2490": "basic_processor",
  "2491": "advanced_processor",
  "2492": "basic_processor",
  "2493": "basic_processor",
  "2494": "advanced_processor",
  "2505": "command_center",
  "2524": "command_center",
  "2525": "command_center",
  "2533": "command_center",
  "2534": "command_center",
  "2535": "storage",
  "2536": "storage",
  "2541": "storage",
  "2542": "launchpad",
  "2543": "launchpad",
  "2544": "launchpad",
  "2549": "command_center",
  "2550": "command_center",
  "2551": "command_center",
  "2552": "launchpad",
  "2555": "launchpad",
  "2556": "launchpad",
  "2557": "launchpad",
  "2558": "storage",
  "2560": "storage",
  "2561": "storage",
  "2562": "storage",
  "2574": "command_center",
  "2576": "command_center",
  "2577": "command_center",
  "2578": "command_center",
  "2581": "command_center",
  "2582": "command_center",
  "2585": "command_center",
  "2586": "command_center",
  "2848": "extractor",
  "3060": "extractor",
  "3061": "extractor",
  "3062": "extractor",
  "3063": "extractor",
  "3064": "extractor",
  "3067": "extractor",
  "3068": "extractor",
  "3388": "advanced_processor",
  "3964": "command_center",
  "4093": "command_center",
  "17787": "storage",
  "19560": "storage",
  "19622": "storage",
  "23240": "storage",
  "25377": "storage",
  "25402": "storage",
  "26240": "storage",
  "26704": "storage",
  "28871": "storage",
  "28873": "storage",
  "28875": "storage",
  "28877": "storage",
  "32206": "storage",
  "50127": "storage",
  "59758": "command_center",
  "60174": "storage"
}

export const PLANET_TYPES: Record<string, string> = {
  "barren": "Barren",
  "gas": "Gas",
  "ice": "Ice",
  "lava": "Lava",
  "oceanic": "Oceanic",
  "plasma": "Plasma",
  "storm": "Storm",
  "temperate": "Temperate"
}

export const PLANET_TYPE_IDS: Record<string, number> = {
  "temperate": 11,
  "ice": 12,
  "gas": 13,
  "oceanic": 2014,
  "lava": 2015,
  "barren": 2016,
  "storm": 2017,
  "plasma": 2063
}

export const PI_COMMODITY_VOLUME: Record<number, number> = {
  "44": 0.75,
  "2073": 0.005,
  "2267": 0.005,
  "2268": 0.005,
  "2270": 0.005,
  "2272": 0.005,
  "2286": 0.005,
  "2287": 0.005,
  "2288": 0.005,
  "2305": 0.005,
  "2306": 0.005,
  "2307": 0.005,
  "2308": 0.005,
  "2309": 0.005,
  "2310": 0.005,
  "2311": 0.005,
  "2312": 0.75,
  "2317": 0.75,
  "2319": 0.75,
  "2321": 0.75,
  "2327": 0.75,
  "2328": 0.75,
  "2329": 0.75,
  "2344": 3,
  "2345": 3,
  "2346": 3,
  "2348": 3,
  "2349": 3,
  "2351": 3,
  "2352": 3,
  "2354": 3,
  "2358": 3,
  "2360": 3,
  "2361": 3,
  "2366": 3,
  "2367": 3,
  "2389": 0.19,
  "2390": 0.19,
  "2392": 0.19,
  "2393": 0.19,
  "2395": 0.19,
  "2396": 0.19,
  "2397": 0.19,
  "2398": 0.19,
  "2399": 0.19,
  "2400": 0.19,
  "2401": 0.19,
  "2463": 0.75,
  "2867": 50,
  "2868": 50,
  "2869": 50,
  "2870": 50,
  "2871": 50,
  "2872": 50,
  "2875": 50,
  "2876": 50,
  "3645": 0.19,
  "3683": 0.19,
  "3689": 0.75,
  "3691": 0.75,
  "3693": 0.75,
  "3695": 0.75,
  "3697": 0.75,
  "3725": 0.75,
  "3775": 0.75,
  "3779": 0.19,
  "3828": 0.75,
  "9828": 0.19,
  "9830": 0.75,
  "9832": 0.75,
  "9834": 3,
  "9836": 0.75,
  "9838": 0.75,
  "9840": 0.75,
  "9842": 0.75,
  "9846": 3,
  "9848": 3,
  "12836": 3,
  "15317": 0.75,
  "17136": 3,
  "17392": 3,
  "17898": 3,
  "28974": 3
}

export const PIN_CAPACITY_M3: Record<number, number> = {
  "2129": 500,
  "2130": 500,
  "2131": 500,
  "2132": 500,
  "2133": 500,
  "2134": 500,
  "2135": 500,
  "2136": 500,
  "2137": 500,
  "2138": 500,
  "2139": 500,
  "2140": 500,
  "2141": 500,
  "2142": 500,
  "2143": 500,
  "2144": 500,
  "2145": 500,
  "2146": 500,
  "2147": 500,
  "2148": 500,
  "2149": 500,
  "2150": 500,
  "2151": 500,
  "2152": 500,
  "2153": 500,
  "2154": 500,
  "2155": 500,
  "2156": 500,
  "2157": 500,
  "2158": 500,
  "2159": 500,
  "2160": 500,
  "2254": 500,
  "2256": 10000,
  "2257": 12000,
  "2469": 0,
  "2470": 0,
  "2471": 0,
  "2472": 0,
  "2473": 0,
  "2474": 0,
  "2475": 0,
  "2480": 0,
  "2481": 0,
  "2482": 0,
  "2483": 0,
  "2484": 0,
  "2485": 0,
  "2490": 0,
  "2491": 0,
  "2492": 0,
  "2493": 0,
  "2494": 0,
  "2505": 500,
  "2524": 500,
  "2525": 500,
  "2533": 500,
  "2534": 500,
  "2535": 12000,
  "2536": 12000,
  "2541": 12000,
  "2542": 10000,
  "2543": 10000,
  "2544": 10000,
  "2549": 500,
  "2550": 500,
  "2551": 500,
  "2552": 10000,
  "2555": 10000,
  "2556": 10000,
  "2557": 10000,
  "2558": 12000,
  "2560": 12000,
  "2561": 12000,
  "2562": 12000,
  "2574": 500,
  "2576": 500,
  "2577": 500,
  "2578": 500,
  "2581": 500,
  "2582": 500,
  "2585": 500,
  "2586": 500,
  "2848": 0,
  "3060": 0,
  "3061": 0,
  "3062": 0,
  "3063": 0,
  "3064": 0,
  "3067": 0,
  "3068": 0,
  "3388": 0,
  "3964": 25000,
  "4093": 500,
  "17787": 8850,
  "19560": 8850,
  "19622": 8850,
  "23240": 8850,
  "25377": 8850,
  "25402": 10000,
  "26240": 8850,
  "26704": 8850,
  "28871": 2700,
  "28873": 2700,
  "28875": 2700,
  "28877": 2700,
  "32206": 2700,
  "50127": 12000,
  "59758": 500,
  "60174": 12000
}

export const TIER_BASE_VALUE: Record<PiCommodityTier, number> = {
  "0": 5,
  "1": 400,
  "2": 7200,
  "3": 60000,
  "4": 1200000
}

export function getSchematicById(schematicId: number): PiSchematic | undefined {
  return PI_SCHEMATICS[schematicId]
}

export function getCommodityTier(typeId: number): PiCommodityTier | undefined {
  return PI_COMMODITY_TIER[typeId]
}

export function getCommodityName(typeId: number): string {
  return PI_COMMODITY_NAMES[typeId] ?? `Type ${typeId}`
}

export function getPinRole(typeId: number): PiPinRole {
  return PIN_ROLES[typeId] ?? 'unknown'
}

const PIN_ROLE_DISPLAY: Record<PiPinRole, string> = {
  command_center: 'Command Center',
  extractor: 'Extractor Control Unit',
  basic_processor: 'Basic Industry Facility',
  advanced_processor: 'Advanced Industry Facility',
  high_tech_processor: 'High-Tech Production Plant',
  storage: 'Storage Facility',
  launchpad: 'Launchpad',
  link: 'Link',
  unknown: 'Planetary Structure',
}

/** EVE structure name for a pin type_id (DB name preferred at enrich time). */
export function getPinStructureName(typeId: number): string {
  return PIN_ROLE_DISPLAY[getPinRole(typeId)]
}

export function getCommodityVolume(typeId: number): number {
  return PI_COMMODITY_VOLUME[typeId] ?? 0.01
}

export function getPinCapacityM3(typeId: number): number {
  const role = getPinRole(typeId)
  if (PIN_CAPACITY_M3[typeId] != null) return PIN_CAPACITY_M3[typeId]
  if (role === 'command_center') return 500
  if (role === 'launchpad') return 10_000
  if (role === 'storage') return 12_000
  return 0
}

export function getPlanetTypeId(planetType: string): number | undefined {
  return PLANET_TYPE_IDS[planetType]
}
