import { buildCriteria } from './types'

export const DEFAULT_MEDALS = [
  // === TIME-BASED (hours) ===
  {
    id: 'new_eden_explorer',
    name: 'New Eden Explorer',
    description: 'Complete your first activity in EasyEve',
    icon: '🚀',
    tier: 'bronze' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'first_activity', value: 1 }),
  },
  {
    id: 'stellar_pioneer',
    name: 'Stellar Pioneer',
    description: 'Spend 10 hours in activities',
    icon: '⭐',
    tier: 'bronze' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'hours', value: 10 }),
  },
  {
    id: 'galactic_wanderer',
    name: 'Galactic Wanderer',
    description: 'Spend 100 hours in activities',
    icon: '🌌',
    tier: 'silver' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'hours', value: 100 }),
  },
  {
    id: 'cosmos_veteran',
    name: 'Cosmos Veteran',
    description: 'Spend 1000 hours in activities',
    icon: '🏆',
    tier: 'gold' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'hours', value: 1000 }),
  },
  {
    id: 'legendary_pilot',
    name: 'Legendary Pilot',
    description: 'Spend 5000 hours in activities',
    icon: '👑',
    tier: 'platinum' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'hours', value: 5000 }),
  },

  // === MINING COUNT ===
  {
    id: 'asteroid_harvester',
    name: 'Asteroid Harvester',
    description: 'Complete 10 mining activities',
    icon: '💎',
    tier: 'bronze' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 10, activity: 'mining' }),
  },
  {
    id: 'belt_commander',
    name: 'Belt Commander',
    description: 'Complete 100 mining activities',
    icon: '⛏️',
    tier: 'silver' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 100, activity: 'mining' }),
  },
  {
    id: 'ore_tycoon',
    name: 'Ore Tycoon',
    description: 'Complete 1000 mining activities',
    icon: '💰',
    tier: 'gold' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 1000, activity: 'mining' }),
  },
  {
    id: 'mining_magnate',
    name: 'Mining Magnate',
    description: 'Complete 5000 mining activities',
    icon: '🏭',
    tier: 'platinum' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 5000, activity: 'mining' }),
  },

  // === RATTING COUNT ===
  {
    id: 'fright_hunter',
    name: 'Frigate Hunter',
    description: 'Complete 10 ratting activities',
    icon: '⚔️',
    tier: 'bronze' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 10, activity: 'ratting' }),
  },
  {
    id: 'cruiser_breaker',
    name: 'Cruiser Breaker',
    description: 'Complete 100 ratting activities',
    icon: '🛸',
    tier: 'silver' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 100, activity: 'ratting' }),
  },
  {
    id: 'battleship_bane',
    name: 'Battleship Bane',
    description: 'Complete 1000 ratting activities',
    icon: '💣',
    tier: 'gold' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 1000, activity: 'ratting' }),
  },
  {
    id: 'capsuleer_elite',
    name: 'Capsuleer Elite',
    description: 'Complete 5000 ratting activities',
    icon: '🎖️',
    tier: 'platinum' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 5000, activity: 'ratting' }),
  },

  // === EXPLORATION COUNT ===
  {
    id: 'scout',
    name: 'Scout',
    description: 'Complete 10 exploration activities',
    icon: '🔭',
    tier: 'bronze' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 10, activity: 'exploration' }),
  },
  {
    id: 'discoverer',
    name: 'Discoverer',
    description: 'Complete 100 exploration activities',
    icon: '🗺️',
    tier: 'silver' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 100, activity: 'exploration' }),
  },
  {
    id: 'archaeologist',
    name: 'Archaeologist',
    description: 'Complete 1000 exploration activities',
    icon: '🏛️',
    tier: 'gold' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 1000, activity: 'exploration' }),
  },
  {
    id: 'explorer_supreme',
    name: 'Explorer Supreme',
    description: 'Complete 5000 exploration activities',
    icon: '🌟',
    tier: 'platinum' as const,
    type: 'instant' as const,
    criteria: buildCriteria({ type: 'count', value: 5000, activity: 'exploration' }),
  },

  // === RANKING (Daily) ===
  {
    id: 'daily_top_miner',
    name: 'Daily Top Miner',
    description: 'Reach top 10 in daily mining ranking',
    icon: '🥇',
    tier: 'gold' as const,
    type: 'daily' as const,
    criteria: buildCriteria({ type: 'ranking', value: 10, activity: 'mining' }),
  },
  {
    id: 'daily_top_ratter',
    name: 'Daily Top Ratter',
    description: 'Reach top 10 in daily ratting ranking',
    icon: '🏅',
    tier: 'gold' as const,
    type: 'daily' as const,
    criteria: buildCriteria({ type: 'ranking', value: 10, activity: 'ratting' }),
  },

  // === RANKING (Weekly) ===
  {
    id: 'weekly_top_miner',
    name: 'Weekly Top Miner',
    description: 'Reach top 10 in weekly mining ranking',
    icon: '🥈',
    tier: 'gold' as const,
    type: 'weekly' as const,
    criteria: buildCriteria({ type: 'ranking', value: 10, activity: 'mining' }),
  },
  {
    id: 'weekly_top_ratter',
    name: 'Weekly Top Ratter',
    description: 'Reach top 10 in weekly ratting ranking',
    icon: '🎖️',
    tier: 'gold' as const,
    type: 'weekly' as const,
    criteria: buildCriteria({ type: 'ranking', value: 10, activity: 'ratting' }),
  },

  // === RANKING (Monthly) ===
  {
    id: 'monthly_ace_miner',
    name: 'Monthly Ace Miner',
    description: 'Reach top 5 in monthly mining ranking',
    icon: '🏆',
    tier: 'platinum' as const,
    type: 'monthly' as const,
    criteria: buildCriteria({ type: 'ranking', value: 5, activity: 'mining' }),
  },
  {
    id: 'monthly_ace_ratter',
    name: 'Monthly Ace Ratter',
    description: 'Reach top 5 in monthly ratting ranking',
    icon: '👑',
    tier: 'platinum' as const,
    type: 'monthly' as const,
    criteria: buildCriteria({ type: 'ranking', value: 5, activity: 'ratting' }),
  },
] as const