/**
 * AUTO-GENERATED by scripts/generate-pi-jf.ts — do not edit manually.
 * Generated at: 2026-07-31T15:05:22.842Z
 *
 * Jump freighter facts for the PI freight model, straight from the official CCP
 * SDE: hull list from the "Jump Freighter" group, cargo m³ from the type's
 * `capacity`, and the isotope from the `jumpDriveConsumptionType` dogma
 * attribute (id 866) — never inferred from the hull's race.
 *
 * Client-safe: pure data, no imports. The freight form needs it in the browser.
 */

export interface PiJumpFreighter {
  typeId: number
  name: string
  /** SDE raceID of the hull. Informational — the isotope comes from dogma. */
  raceId: number | null
  /** Base cargo hold, m³. The real load the player carries can be smaller. */
  cargoM3: number
  /** Isotope the jump drive burns (dogma jumpDriveConsumptionType). */
  isotopeTypeId: number
  isotopeName: string
  isotopeVolumeM3: number
}

export const PI_JUMP_FREIGHTERS: PiJumpFreighter[] = [
  {
    "typeId": 28848,
    "name": "Anshar",
    "raceId": 8,
    "cargoM3": 137500,
    "isotopeTypeId": 17887,
    "isotopeName": "Oxygen Isotopes",
    "isotopeVolumeM3": 0.03
  },
  {
    "typeId": 28850,
    "name": "Ark",
    "raceId": 4,
    "cargoM3": 135000,
    "isotopeTypeId": 16274,
    "isotopeName": "Helium Isotopes",
    "isotopeVolumeM3": 0.03
  },
  {
    "typeId": 28846,
    "name": "Nomad",
    "raceId": 2,
    "cargoM3": 132000,
    "isotopeTypeId": 17889,
    "isotopeName": "Hydrogen Isotopes",
    "isotopeVolumeM3": 0.03
  },
  {
    "typeId": 28844,
    "name": "Rhea",
    "raceId": 1,
    "cargoM3": 144000,
    "isotopeTypeId": 17888,
    "isotopeName": "Nitrogen Isotopes",
    "isotopeVolumeM3": 0.03
  }
]

const BY_TYPE_ID = new Map<number, PiJumpFreighter>(
  PI_JUMP_FREIGHTERS.map((jf) => [jf.typeId, jf])
)

/** The hull, or undefined when the stored typeId is not a jump freighter. */
export function getJumpFreighter(typeId: number): PiJumpFreighter | undefined {
  return BY_TYPE_ID.get(typeId)
}

/** Every isotope a configured JF could need — the set to price on the books. */
export const PI_ISOTOPE_TYPE_IDS: number[] = [
  ...new Set(PI_JUMP_FREIGHTERS.map((jf) => jf.isotopeTypeId)),
].sort((a, b) => a - b)
