/**
 * Machine-readable codes for Fits API v2 responses and logs.
 */
export const FitsV2Codes = {
  OK: 'OK',
  UNAUTHORIZED: 'UNAUTHORIZED',
  PREMIUM_REQUIRED: 'PREMIUM_REQUIRED',
  INVALID_BODY: 'INVALID_BODY',
  SHIP_NOT_FOUND: 'SHIP_NOT_FOUND',
  SHIP_DATA_INCOMPLETE: 'SHIP_DATA_INCOMPLETE',
  MODULE_NOT_IN_DATABASE: 'MODULE_NOT_IN_DATABASE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MUTATION_REJECTED: 'MUTATION_REJECTED',
  EFT_INVALID: 'EFT_INVALID',
  EFT_PARSE_FAILED: 'EFT_PARSE_FAILED',
  IMPORT_VALIDATION_FAILED: 'IMPORT_VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type FitsV2Code = (typeof FitsV2Codes)[keyof typeof FitsV2Codes]
